language: python
virtualenv:
    system_site_packages: false
env:
    - DISTRIB="conda" PYTHON_VERSION="3.4" NUMPY_VERSION="1.8.1"
      SCIPY_VERSION="0.14.0" NETWORKX_VERSION="1.8.1" COVERAGE="true"
      PANDAS_VERSION="0.15.1"

before_install:
    - uname -a
    - free -m
    - df -h
    - ulimit -a
install: source continous_integration/install.sh
script: nosetests --with-coverage --cover-package=pgmpy
after_success:
    coveralls
notifications:
    email: false
