language: python
python:
    - "3.4"
virtualenv:
    system_site_packages: false
before_install:
    - uname -a
    - free -m
    - df -h
    - ulimit -a
    - sudo apt-get update
#    - sudo apt-get build-dep -qq python3-numpy
#    - sudo apt-get install python3-numpy
#    - sudo apt-get build-dep -qq python3-scipy
#    - curl http://python-distribute.org/distribute_setup.py | sudo python3
#    - curl https://raw.github.com/pypa/pip/master/contrib/get-pip.py | sudo python3

install:
#    - "pip3 -q install cython"
    - "pip -q install networkx"
    - "pip install numpy"
#    - "pip3  install scipy --upgrade"
    - "pip -q install nose"
#    - "pip3 -q install coveralls"
    - "sudo python setup.py develop"
script: nosetests3 --with-coverage --cover-package=pgmpy/pgmpy
after_success:
    coveralls
notifications:
    email: false
